### ISSUE TITLE
Standardize README for poutils projects ?

### ISSUE THREAD

**Issue by Seluj78** [AFPy/poutils#11]
cc @JulienPalard and @vpoulailleau ! What do you think about making a standard looking README for our poutils projects ? Or even better I think, making an org ?

Cheers

**Comment by Seluj78** [comment]
🏓 @JulienPalard @vpoulailleau :) I have some freetime so I would be able to work on it 🔥

**Comment by vpoulailleau** [comment]
I'm OK for both!

For READMEs, we should agree on a table of content, but I assume current READMEs give almost the same kind of information.

For the organization, I never did the transfer of one of my projects to a organization. But once the organization is created, I'm OK to do the transfer.

That depends also on @JulienPalard 's choice for the projects he created.

**Comment by JulienPalard** [comment]
For the org what about the AFPy org?

For the standard README it's probably a good idea, and we should not create a new standard but try to pick something existing and nice looking.

**Comment by Seluj78** [comment]
> For the org what about the AFPy org?

I was thinking a new one but the afpy one is fine! I'll check if I have all the rights necessary

> For the standard README it's probably a good idea, and we should not create a new standard but try to pick something existing and nice looking.

Sure! We can look around for nice open source packages and find a readme we like

**Comment by Seluj78** [comment]
https://discuss.afpy.org/t/migration-des-outils-de-traductions-vers-afpy-sur-github/73

**Comment by Seluj78** [comment]
https://github.com/AFPy/Potodo/pull/107
